In [ ]:
# 匯入 pandas，後面會用 DataFrame 讀取與整理資料
import pandas as pd
# 匯入 train_test_split，把資料分成「訓練資料」和「測試資料」
from sklearn.model_selection import train_test_split
# 匯入 StandardScaler，讓不同數值範圍的欄位先做標準化
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
# 匯入 joblib，用來儲存與重新載入模型
import joblib
# 匯入 Path，用來建立 models 資料夾
from pathlib import Path

In [19]:
df = pd.read_csv("./Advertising.csv")
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [20]:
df.tail()

        TV  radio  newspaper  sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [21]:
features = ["TV","radio","newspaper"]
X = df[features]
X.head()

      TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [22]:
y = df["sales"]
print(y.head())

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((160, 3), (40, 3), (160,), (40,))

In [24]:
linear_scaler = StandardScaler()
X_train_scaled = linear_scaler.fit_transform(X_train)
X_test_scale = linear_scaler.transform(X_test)

In [27]:
linear_model = LinearRegression()
v = linear_model.fit(X_train_scaled,y_train)
print(v)

LinearRegression()

In [28]:
from sklearn.metrics import mean_squared_error
pred = linear_model.predict(X_test_scale)
mse = mean_squared_error(y_test,pred)
print("mse:",mse)

mse: 3.174097353976105

## 如何預測

In [31]:
new_ad = pd.DataFrame([{"TV":150.0,"radio":30.0,"newspaper":20.0}])
new_ad = linear_scaler.transform(new_ad)
new_sales = linear_model.predict(new_ad)[0]
print(new_sales)

15.419568872288721

In [32]:
joblib.dump((linear_model,linear_scaler),"linear_model.pkl")

['linear_model.pkl']