In [194]:
import pandas as pd
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
drop=pd.read_csv(StringIO(csv_data))
print(drop)
drop2 = drop.dropna(axis=1,thresh=4)
print(drop2)

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
      A     C
0   2.0   4.0
1   6.0   6.0
2  10.0  11.0
3   NaN   NaN
4   3.0   3.0
5   NaN   NaN

## 填充遺失值

In [195]:
import pandas as pd
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
fill=pd.read_csv(StringIO(csv_data))
print(fill)
fill_zero =  fill.fillna(0)
print(fill_zero)
fill_zero = fill.fillna(0,limit=2)
print(fill_zero)
print("="*50)
fill2 =  fill.ffill()# 如果當前欄位是NaN  向上一筆同欄直到非NaN的值 寫入目前欄位
print(fill2)
print("="*50)
fill3 = fill.bfill()# 如果當前欄位是NaN  向下一筆同欄直到非NaN的值 寫入目前欄位
print(fill3)
print("="*50)

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
      A     B     C    D    E
0   2.0   3.0   4.0  5.0  0.0
1   6.0  34.0   6.0  0.0  0.0
2  10.0   0.0  11.0  8.0  0.0
3   0.0   0.0   0.0  0.0  0.0
4   3.0   0.0   3.0  0.0  0.0
5   0.0   5.0   0.0  0.0  0.0
      A     B     C    D    E
0   2.0   3.0   4.0  5.0  0.0
1   6.0  34.0   6.0  0.0  0.0
2  10.0   0.0  11.0  8.0  NaN
3   0.0   0.0   0.0  0.0  NaN
4   3.0   NaN   3.0  NaN  NaN
5   0.0   5.0   0.0  NaN  NaN
==================================================
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  5.0 NaN
2  10.0  34.0  11.0  8.0 NaN
3  10.0  34.0  11.0  8.0 NaN
4   3.0  34.0   3.0  8.0 NaN
5   3.0   5.0   3.0  8.0 NaN
==================================================
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  8.0 NaN
2  10.0   5.0  11.0  8.0 NaN
3   3.0   5.0   3.0  NaN NaN
4   3.0   5.0   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
==================================================

In [196]:
import pandas as pd
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
fill=pd.read_csv(StringIO(csv_data))
print(fill)
fillmean = fill.mean()
print(fillmean)
#print(fillmean["B"])
print("=================")
for x in fill:
    #print(fill[x])     
     fill[x] = fill[x].fillna(fillmean.loc[x])
print("=================")     
print(fill)

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
A     5.25
B    14.00
C     6.00
D     6.50
E      NaN
dtype: float64
=================
=================
       A     B     C    D   E
0   2.00   3.0   4.0  5.0 NaN
1   6.00  34.0   6.0  6.5 NaN
2  10.00  14.0  11.0  8.0 NaN
3   5.25  14.0   6.0  6.5 NaN
4   3.00  14.0   3.0  6.5 NaN
5   5.25   5.0   6.0  6.5 NaN

## Pand群組

In [197]:
import pandas as pd
import numpy as np
company=["A","B","C"]
data1=pd.DataFrame(
{"company":[company[x] for x in np.random.randint(0,len(company),20)],
"salary":np.random.randint(5,50,20),
"age":np.random.randint(15,50,20)}    
)
print(data1)

   company  salary  age
0        C      42   21
1        B      42   40
2        B      38   22
3        C      10   38
4        B      49   20
5        A      11   31
6        B      23   40
7        A      21   15
8        C      48   34
9        C      29   21
10       A      29   44
11       A      48   23
12       B      29   40
13       B      17   16
14       A      43   22
15       C      24   23
16       A      49   19
17       A      11   21
18       A      15   19
19       B      31   41

In [198]:
group = data1.groupby("company")
print(list(group))

[('A',    company  salary  age
5        A      11   31
7        A      21   15
10       A      29   44
11       A      48   23
14       A      43   22
16       A      49   19
17       A      11   21
18       A      15   19), ('B',    company  salary  age
1        B      42   40
2        B      38   22
4        B      49   20
6        B      23   40
12       B      29   40
13       B      17   16
19       B      31   41), ('C',    company  salary  age
0        C      42   21
3        C      10   38
8        C      48   34
9        C      29   21
15       C      24   23)]

In [199]:
print(group.size())
print(group.first())
print(group.last())

company
A    8
B    7
C    5
dtype: int64
         salary  age
company
A            11   31
B            42   40
C            42   21
         salary  age
company
A            15   19
B            31   41
C            24   23

In [200]:
import pandas as pd
fortune = pd.read_csv("fortune1000.csv",index_col="Rank")
print(fortune.head())#預設前5筆
sector = fortune.groupby("Sector")
print("="*50)
print(sector.size())

                 Company       Sector  \
Rank
1                Walmart    Retailing
2            Exxon Mobil       Energy
3                  Apple   Technology
4     Berkshire Hathaway   Financials
5               McKesson  Health Care

                                      Industry           Location  Revenue  \
Rank
1                        General Merchandisers    Bentonville, AR   482130
2                           Petroleum Refining         Irving, TX   246204
3                  Computers, Office Equipment      Cupertino, CA   233715
4     Insurance: Property and Casualty (Stock)          Omaha, NE   210821
5                     Wholesalers: Health Care  San Francisco, CA   181241

      Profits  Employees
Rank
1       14694    2300000
2       16150      75600
3       53394     110000
4       24083     331000
5        1476      70400
==================================================
Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

In [201]:
print(sector.sum(numeric_only=True))
print(sector.mean(numeric_only=True))

                              Revenue  Profits  Employees
Sector
Aerospace & Defense            357940    28742     968057
Apparel                         95968     8236     346397
Business Services              272195    28227    1361050
Chemicals                      243897    22628     463651
Energy                        1517809   -73447    1188927
Engineering & Construction     153983     5304     406708
Financials                    2217159   260209    3359948
Food and Drug Stores           483769    16759    1395398
Food, Beverages & Tobacco      555967    51417    1211632
Health Care                   1614707   106114    2678289
Hotels, Resturants & Leisure   169546    20697    2484245
Household Products             234737    14428     646038
Industrials                    497581    20764    1545229
Materials                      259145     4428     638123
Media                          220764    24347     550314
Motor Vehicles & Parts         482540    25898    1082560
Retailing                     1465076    47830    6227629
Technology                    1377600   180473    3578949
Telecommunications             461834    48637     832468
Transportation                 408508    44169    1536793
Wholesalers                    444800     8233     525597
                                   Revenue      Profits     Employees
Sector
Aerospace & Defense           17897.000000  1437.100000  48402.850000
Apparel                        6397.866667   549.066667  23093.133333
Business Services              5337.156863   553.470588  26687.254902
Chemicals                      8129.900000   754.266667  15455.033333
Energy                        12441.057377  -602.024590   9745.303279
Engineering & Construction     5922.423077   204.000000  15642.615385
Financials                    15950.784173  1872.007194  24172.287770
Food and Drug Stores          32251.266667  1117.266667  93026.533333
Food, Beverages & Tobacco     12929.465116  1195.744186  28177.488372
Health Care                   21529.426667  1414.853333  35710.520000
Hotels, Resturants & Leisure   6781.840000   827.880000  99369.800000
Household Products             8383.464286   515.285714  23072.785714
Industrials                   10816.978261   451.391304  33591.934783
Materials                      6026.627907   102.976744  14840.069767
Media                          8830.560000   973.880000  22012.560000
Motor Vehicles & Parts        20105.833333  1079.083333  45106.666667
Retailing                     18313.450000   597.875000  77845.362500
Technology                    13505.882353  1769.343137  35087.735294
Telecommunications            30788.933333  3242.466667  55497.866667
Transportation                11347.444444  1226.916667  42688.694444
Wholesalers                   11120.000000   205.825000  13139.925000

In [202]:
df_numeric = fortune.select_dtypes(include="number")
print(df_numeric)
df_not_numeric =  fortune.select_dtypes(exclude="number")
print(df_not_numeric)

      Revenue  Profits  Employees
Rank
1      482130    14694    2300000
2      246204    16150      75600
3      233715    53394     110000
4      210821    24083     331000
5      181241     1476      70400
...       ...      ...        ...
996      1902      -47       3448
997      1898      172       2646
997      1898      172       2646
999      1896      161      21200
1000     1895       46       5480

[1000 rows x 3 columns]
                         Company                        Sector  \
Rank
1                        Walmart                     Retailing
2                    Exxon Mobil                        Energy
3                          Apple                    Technology
4             Berkshire Hathaway                    Financials
5                       McKesson                   Health Care
...                          ...                           ...
996   New York Community Bancorp                    Financials
997    Portland General Electric                        Energy
997    Portland General Electric                        Energy
999                      Wendy’s  Hotels, Resturants & Leisure
1000           Briggs & Stratton                   Industrials

                                      Industry           Location
Rank
1                        General Merchandisers    Bentonville, AR
2                           Petroleum Refining         Irving, TX
3                  Computers, Office Equipment      Cupertino, CA
4     Insurance: Property and Casualty (Stock)          Omaha, NE
5                     Wholesalers: Health Care  San Francisco, CA
...                                        ...                ...
996                           Commercial Banks       Westbury, NY
997                Utilities: Gas and Electric       Portland, OR
997                Utilities: Gas and Electric       Portland, OR
999                              Food Services         Dublin, OH
1000                      Industrial Machinery      Wauwatosa, WI

[1000 rows x 4 columns]

In [203]:
sector.agg("sum",numeric_only=True)

                              Revenue  Profits  Employees
Sector
Aerospace & Defense            357940    28742     968057
Apparel                         95968     8236     346397
Business Services              272195    28227    1361050
Chemicals                      243897    22628     463651
Energy                        1517809   -73447    1188927
Engineering & Construction     153983     5304     406708
Financials                    2217159   260209    3359948
Food and Drug Stores           483769    16759    1395398
Food, Beverages & Tobacco      555967    51417    1211632
Health Care                   1614707   106114    2678289
Hotels, Resturants & Leisure   169546    20697    2484245
Household Products             234737    14428     646038
Industrials                    497581    20764    1545229
Materials                      259145     4428     638123
Media                          220764    24347     550314
Motor Vehicles & Parts         482540    25898    1082560
Retailing                     1465076    47830    6227629
Technology                    1377600   180473    3578949
Telecommunications             461834    48637     832468
Transportation                 408508    44169    1536793
Wholesalers                    444800     8233     525597

In [204]:
sector.agg({"Revenue":["size","sum","mean"],"Employees":"mean"})

                             Revenue                            Employees
                                size      sum          mean          mean
Sector
Aerospace & Defense               20   357940  17897.000000  48402.850000
Apparel                           15    95968   6397.866667  23093.133333
Business Services                 51   272195   5337.156863  26687.254902
Chemicals                         30   243897   8129.900000  15455.033333
Energy                           122  1517809  12441.057377   9745.303279
Engineering & Construction        26   153983   5922.423077  15642.615385
Financials                       139  2217159  15950.784173  24172.287770
Food and Drug Stores              15   483769  32251.266667  93026.533333
Food, Beverages & Tobacco         43   555967  12929.465116  28177.488372
Health Care                       75  1614707  21529.426667  35710.520000
Hotels, Resturants & Leisure      25   169546   6781.840000  99369.800000
Household Products                28   234737   8383.464286  23072.785714
Industrials                       46   497581  10816.978261  33591.934783
Materials                         43   259145   6026.627907  14840.069767
Media                             25   220764   8830.560000  22012.560000
Motor Vehicles & Parts            24   482540  20105.833333  45106.666667
Retailing                         80  1465076  18313.450000  77845.362500
Technology                       102  1377600  13505.882353  35087.735294
Telecommunications                15   461834  30788.933333  55497.866667
Transportation                    36   408508  11347.444444  42688.694444
Wholesalers                       40   444800  11120.000000  13139.925000

In [205]:
import pandas as pd
auto_price = pd.read_csv("Automobile.csv")
auto_price.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    str
 2   make               205 non-null    str
 3   fuel-type          205 non-null    str
 4   aspiration         205 non-null    str
 5   num-of-doors       205 non-null    str
 6   body-style         205 non-null    str
 7   drive-wheels       205 non-null    str
 8   engine-location    205 non-null    str
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    str
 15  num-of-cylinders   205 non-null    str
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    str
 18  bore               205 non-null    str
 19  stroke             205 non-null    str
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    str
 22  peak-rpm           205 non-null    str
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    str
dtypes: float64(5), int64(5), str(16)
memory usage: 54.4 KB

In [206]:
auto_price.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [207]:
list1 = []
for col in auto_price:
    for filed1 in auto_price[col]:
        if filed1 == "?":
            list1.append(col)
            break
print(list1)

['normalized-losses', 'num-of-doors', 'bore', 'stroke', 'horsepower', 'peak-rpm', 'price']

In [208]:
import numpy as np
for column in list1:
    auto_price.loc[auto_price[column] == "?",column] = np.nan
print(auto_price.isnull().any())    
auto_price.info()

symboling            False
normalized-losses     True
make                 False
fuel-type            False
aspiration           False
num-of-doors          True
body-style           False
drive-wheels         False
engine-location      False
wheel-base           False
length               False
width                False
height               False
curb-weight          False
engine-type          False
num-of-cylinders     False
engine-size          False
fuel-system          False
bore                  True
stroke                True
compression-ratio    False
horsepower            True
peak-rpm              True
city-mpg             False
highway-mpg          False
price                 True
dtype: bool
<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    str
 2   make               205 non-null    str
 3   fuel-type          205 non-null    str
 4   aspiration         205 non-null    str
 5   num-of-doors       203 non-null    str
 6   body-style         205 non-null    str
 7   drive-wheels       205 non-null    str
 8   engine-location    205 non-null    str
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    str
 15  num-of-cylinders   205 non-null    str
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    str
 18  bore               201 non-null    str
 19  stroke             201 non-null    str
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    str
 22  peak-rpm           203 non-null    str
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    str
dtypes: float64(5), int64(5), str(16)
memory usage: 54.6 KB

In [209]:
print(auto_price.dtypes)
print(auto_price.isnull().sum())

symboling              int64
normalized-losses        str
make                     str
fuel-type                str
aspiration               str
num-of-doors             str
body-style               str
drive-wheels             str
engine-location          str
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type              str
num-of-cylinders         str
engine-size            int64
fuel-system              str
bore                     str
stroke                   str
compression-ratio    float64
horsepower               str
peak-rpm                 str
city-mpg               int64
highway-mpg            int64
price                    str
dtype: object
symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [210]:
print(auto_price.shape)
try:
    auto_price = auto_price.drop(["normalized-losses"],axis=1)
except:
    pass

print(auto_price.shape)

(205, 26)
(205, 25)

In [211]:
print(auto_price.isnull().sum())
auto_price = auto_price.dropna(axis=0)
print(auto_price.isnull().sum())

symboling            0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64
symboling            0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [212]:
# list3 = []
# for i in auto_price:
#     if auto_price[i].dtype == "str":
#         try:
#             auto_price[i] = auto_price[i].astype("float")
#             list3.append(i)
#         except:
#             pass
# print(list3)

In [214]:
list3 = []
for i in auto_price:
    if auto_price[i].dtype == "str":
        try:
            auto_price[i] = auto_price[i].astype('float')
            list3.append(i)
        except:
            pass
print(list3)

['bore', 'stroke', 'horsepower', 'peak-rpm', 'price']

In [ ]:
cols4 = []
cols5 = []

for  i in auto_price:
    if auto_price[i].dtype == "str":
        cols4.append(i)
    else:
        cols5.append(i)
print(cols4)
print(cols5) 
#排序 計算內容數量 好用value_counts 
for column in cols4:
    print(auto_price[column].value_counts())

['make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'engine-type', 'num-of-cylinders', 'fuel-system']
['symboling', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-size', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']
make
toyota           32
nissan           18
honda            13
mitsubishi       13
mazda            12
subaru           12
volkswagen       12
peugot           11
volvo            11
bmw               8
dodge             8
mercedes-benz     8
plymouth          7
audi              6
saab              6
porsche           4
alfa-romero       3
chevrolet         3
jaguar            3
isuzu             2
mercury           1
Name: count, dtype: int64
fuel-type
gas       174
diesel     19
Name: count, dtype: int64
aspiration
std      158
turbo     35
Name: count, dtype: int64
num-of-doors
four    112
two      81
Name: count, dtype: int64
body-style
sedan          92
hatchback      63
wagon          24
hardtop         8
convertible     6
Name: count, dtype: int64
drive-wheels
fwd    114
rwd     71
4wd      8
Name: count, dtype: int64
engine-location
front    190
rear       3
Name: count, dtype: int64
engine-type
ohc     141
ohcf     15
ohcv     13
dohc     12
l        12
Name: count, dtype: int64
num-of-cylinders
four      153
six        24
five       10
eight       4
three       1
twelve      1
Name: count, dtype: int64
fuel-system
mpfi    88
2bbl    64
idi     19
1bbl    11
spdi     9
mfi      1
spfi     1
Name: count, dtype: int64